name: teslo_shop
description: "App for Teslo Shop, a shop that sells Tesla products."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  dio: ^5.8.0+1
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.2.1
  flutter_native_splash: ^2.4.6
  flutter_riverpod: ^2.6.1
  flutter_staggered_grid_view: ^0.7.0
  formz: ^0.8.0
  go_router: ^15.1.2
  google_fonts: ^6.2.1
  image_picker: ^1.1.2
  shared_preferences: ^2.5.3

dev_dependencies:
  change_app_package_name: ^1.5.0
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter_native_splash:
  color: "#252829"

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/loaders/
    - assets/images/
    - assets/fonts/montserrat_alternates/
